Open5GS daemon v2.4.4

01/10 18:17:32.199: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
01/10 18:17:32.199: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
01/10 18:17:32.217: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
01/10 18:17:32.218: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
01/10 18:17:32.218: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
Open5GS daemon v2.4.4

01/10 19:14:18.628: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
01/10 19:14:18.628: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
01/10 19:14:18.654: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
01/10 19:14:18.654: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
01/10 19:14:18.654: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
Open5GS daemon v2.4.4

01/10 19:54:37.386: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
01/10 19:54:37.386: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
01/10 19:54:37.402: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
01/10 19:54:37.402: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
01/10 19:54:37.402: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
Open5GS daemon v2.4.4

01/10 20:50:42.921: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
01/10 20:50:42.921: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
01/10 20:50:42.938: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
01/10 20:50:42.938: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
01/10 20:50:42.938: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
01/10 20:51:25.137: [pfcp] INFO: ogs_pfcp_connect() [192.168.0.111]:8805 (../lib/pfcp/path.c:59)
01/10 20:51:25.138: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
01/10 20:53:30.188: [pfcp] ERROR: ogs_pfcp_sendto() failed (101:Network is unreachable) (../lib/pfcp/path.c:115)
01/10 20:53:30.188: [pfcp] ERROR: ogs_pfcp_sendto() failed (../lib/pfcp/xact.c:614)
Open5GS daemon v2.4.4

01/10 20:58:47.389: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
01/10 20:58:47.389: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
01/10 20:58:47.423: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
01/10 20:58:47.423: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
01/10 20:58:47.423: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
01/10 20:59:29.049: [pfcp] INFO: ogs_pfcp_connect() [192.168.0.111]:8805 (../lib/pfcp/path.c:59)
01/10 20:59:29.049: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
01/10 21:01:36.967: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:160)
01/10 21:01:36.967: [gtp] INFO: gtp_connect() [127.0.0.4]:2152 (../lib/gtp/path.c:58)
01/10 21:01:36.967: [upf] INFO: UE F-SEID[CP:0x1 UP:0x2] APN[mec] PDN-Type[1] IPv4[10.46.0.2] IPv6[] (../src/upf/context.c:361)
01/10 21:01:37.472: [gtp] INFO: gtp_connect() [192.168.0.131]:2152 (../lib/gtp/path.c:58)
Open5GS daemon v2.4.4

04/23 18:54:32.718: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
04/23 18:54:32.718: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
04/23 18:54:32.750: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
04/23 18:54:32.750: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
04/23 18:54:32.750: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
04/23 18:55:16.486: [pfcp] INFO: ogs_pfcp_connect() [192.168.0.111]:8805 (../lib/pfcp/path.c:59)
04/23 18:55:16.486: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
Open5GS daemon v2.4.4

06/02 20:44:11.295: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
06/02 20:44:11.295: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
06/02 20:44:11.734: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
06/02 20:44:11.734: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
06/02 20:44:11.741: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
06/02 20:44:50.066: [pfcp] INFO: ogs_pfcp_connect() [192.168.0.111]:8805 (../lib/pfcp/path.c:59)
06/02 20:44:50.066: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
06/02 22:22:53.596: [pfcp] ERROR: ogs_pfcp_sendto() failed (101:Network is unreachable) (../lib/pfcp/path.c:115)
06/02 22:22:53.596: [pfcp] ERROR: ogs_pfcp_xact_commit: Expectation `rv == OGS_OK' failed. (../lib/pfcp/xact.c:573)
Open5GS daemon v2.4.4

06/02 22:26:07.519: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
06/02 22:26:07.519: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
06/02 22:26:07.561: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
06/02 22:26:07.561: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
06/02 22:26:07.566: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
06/02 22:27:49.553: [pfcp] INFO: ogs_pfcp_connect() [192.168.0.111]:8805 (../lib/pfcp/path.c:59)
06/02 22:27:49.553: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
06/02 22:29:57.376: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:160)
06/02 22:29:57.376: [gtp] INFO: gtp_connect() [127.0.0.4]:2152 (../lib/gtp/path.c:58)
06/02 22:29:57.376: [upf] INFO: UE F-SEID[CP:0x1 UP:0x2] APN[mec] PDN-Type[1] IPv4[10.46.0.2] IPv6[] (../src/upf/context.c:361)
06/02 22:29:57.992: [gtp] INFO: gtp_connect() [192.168.0.131]:2152 (../lib/gtp/path.c:58)
06/03 00:53:46.172: [pfcp] ERROR: ogs_pfcp_sendto() failed (101:Network is unreachable) (../lib/pfcp/path.c:115)
06/03 00:53:46.172: [pfcp] ERROR: ogs_pfcp_xact_commit: Expectation `rv == OGS_OK' failed. (../lib/pfcp/xact.c:573)
Open5GS daemon v2.4.4

06/03 01:04:24.870: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
06/03 01:04:24.871: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
06/03 01:04:24.919: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
06/03 01:04:24.919: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
06/03 01:04:24.922: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
06/03 01:06:07.085: [pfcp] INFO: ogs_pfcp_connect() [192.168.0.111]:8805 (../lib/pfcp/path.c:59)
06/03 01:06:07.086: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
06/03 01:08:14.048: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:160)
06/03 01:08:14.049: [gtp] INFO: gtp_connect() [127.0.0.4]:2152 (../lib/gtp/path.c:58)
06/03 01:08:14.049: [upf] INFO: UE F-SEID[CP:0x1 UP:0x2] APN[mec] PDN-Type[1] IPv4[10.46.0.2] IPv6[] (../src/upf/context.c:361)
06/03 01:08:14.520: [gtp] INFO: gtp_connect() [192.168.0.131]:2152 (../lib/gtp/path.c:58)
06/03 01:29:33.727: [pfcp] ERROR: ogs_pfcp_sendto() failed (101:Network is unreachable) (../lib/pfcp/path.c:115)
06/03 01:29:33.727: [pfcp] ERROR: ogs_pfcp_sendto() failed (../lib/pfcp/xact.c:614)
06/03 01:29:34.362: [app] INFO: SIGHUP received (../src/main.c:58)
Open5GS daemon v2.4.4

06/03 01:56:17.344: [app] INFO: Configuration: '/open5gs/install/etc/open5gs/upf.yaml' (../lib/app/ogs-init.c:129)
06/03 01:56:17.344: [app] INFO: File Logging: '/open5gs/install/var/log/open5gs/upf_mec.log' (../lib/app/ogs-init.c:132)
06/03 01:56:17.619: [pfcp] INFO: pfcp_server() [192.168.0.113]:8805 (../lib/pfcp/path.c:30)
06/03 01:56:17.619: [gtp] INFO: gtp_server() [192.168.0.113]:2152 (../lib/gtp/path.c:30)
06/03 01:56:17.636: [app] INFO: UPF initialize...done (../src/upf/app.c:31)
06/03 01:57:59.872: [pfcp] INFO: ogs_pfcp_connect() [192.168.0.111]:8805 (../lib/pfcp/path.c:59)
06/03 01:57:59.875: [upf] INFO: PFCP associated (../src/upf/pfcp-sm.c:173)
06/03 02:00:06.539: [upf] INFO: [Added] Number of UPF-Sessions is now 1 (../src/upf/context.c:160)
06/03 02:00:06.539: [gtp] INFO: gtp_connect() [127.0.0.4]:2152 (../lib/gtp/path.c:58)
06/03 02:00:06.539: [upf] INFO: UE F-SEID[CP:0x1 UP:0x2] APN[mec] PDN-Type[1] IPv4[10.46.0.2] IPv6[] (../src/upf/context.c:361)
06/03 02:00:06.993: [gtp] INFO: gtp_connect() [192.168.0.131]:2152 (../lib/gtp/path.c:58)
